routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('quiz.end');
})->middleware('guest')->name('index');

Route::get('/quiz', function() {
    return view('quiz.start');
})->name('quiz')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('questions', 'QuestionController')->except('show');
Route::resource('questions.answers', 'AnswerController')->except('show', 'index');

Route::get('datatable/questions', 'DatatableController@questions')->name('datatable.questions');
Route::get('datatable/questions/{id}/answers', 'DatatableController@answers')->name('datatable.answers');
Route::get('datatable/users', 'DatatableController@users')->name('datatable.users');
Route::view('bases-y-condiciones', 'quiz.bases')->name('bases');
Route::view('salones-y-barberias-participantes', 'quiz.participantes')->name('participantes');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $casts = [
        'is_correct' => 'boolean'
    ];

    protected $appends = [ 'asset_image'];

    protected $hidden = ['is_correct'];

    public function getAssetImageAttribute()
    {
        return asset("app/$this->image");
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class AnswerController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('auth.admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Question $question)
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Question $question)
    {
        return view('answers.form', compact('question'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $question)
    {
        $answer = new Answer();
        $answer->question_id = $question;
        $answer->image = $request->image->store('images');
        $answer->text = $request->text;
        $answer->is_correct = $request->get('is_correct');
        if($answer->save()){
            return redirect()->route('questions.answers.edit', ['question' => $question, 'answer' => $answer])->with('saved', true);
        } else return redirect()->route('questions.answers.create')->with('saved', false);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question, Answer $answer)
    {
        return view('answers.form', compact('question', 'answer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $question
     * @param Answer $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $question, Answer $answer)
    {
        $answer->question_id = $question;
        if($request->image) $answer->image = $request->image->store('images');
        $answer->text = $request->text;
        $answer->is_correct = $request->get('is_correct');

        if($answer->save()){
            return redirect()->route('questions.answers.edit', ['question' => $question, 'answer' => $answer])->with('saved', true);
        } else return redirect()->route('questions.answers.create')->with('saved', false);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/answers/form.blade.php
@php
    $form_route = isset($answer) ? route('questions.answers.update', ['question' => $question->id, 'answer' => $answer]) : route('questions.answers.store', $question->id);
@endphp

@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-sm-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('questions.index') }}">Listado Preguntas</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('questions.edit', $question) }}">Pregunta</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Respuesta</li>
                </ol>
            </nav>
        </div>
        @if(session()->has('saved') && session('saved'))
            <div class="col-sm-12">
                <div class="alert alert-success" role="alert">
                    Datos guardados correctamente.
                </div>
            </div>
        @elseif(session()->has('saved') && !session('saved'))
            <div class="col-sm-12">
                <div class="alert alert-danger" role="alert">
                    Hubo un problema al guardar.
                </div>
            </div>
        @endif
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">Datos</div>

                <div class="card-body">
                    <form action="{{ $form_route }}" method="POST" enctype="multipart/form-data">
                        @isset($answer)
                            @method('PUT')
                            <img src="{{ asset("app/$answer->image") }}">
                        @endisset
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="content_texto">Imagen</label>
                            <input type="text" name="text" class="form-control" value="{{isset($answer) ? $answer->text : null}}">
                        </div>
                        <div class="form-group">
                            <label for="content_imagen">Texto</label>
                            <input type="file" name="image" class="form-control-file">
                        </div>
                        <div class="form-check">
                            <input type="hidden" name="is_correct" value="0">
                            <input type="checkbox" class="form-check-input" name="is_correct" value="1" @isset($answer) @if($answer->is_correct) checked @endif @endisset>
                            <label class="form-check-label" for="is_correct">¿Respuesta Correcta?</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/answers/image.blade.php
<img src="{{ asset("app/$row->image") }}" class="img-fluid">

resources/views/answers/options.blade.php
<a href="{{ route('questions.answers.edit', [ 'question' => $row->question_id, 'answer' => $row->id ]) }}" class="btn btn-secondary"><i class="text-white fas fa-edit"></i></a>