routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('quiz.end');
})->middleware('guest')->name('index');

Route::get('/quiz', function() {
    return view('quiz.start');
})->name('quiz')->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('questions', 'QuestionController')->except('show');
Route::resource('questions.answers', 'AnswerController')->except('show', 'index');

Route::get('datatable/questions', 'DatatableController@questions')->name('datatable.questions');
Route::get('datatable/questions/{id}/answers', 'DatatableController@answers')->name('datatable.answers');
Route::get('datatable/users', 'DatatableController@users')->name('datatable.users');
Route::view('bases-y-condiciones', 'quiz.bases')->name('bases');
Route::view('salones-y-barberias-participantes', 'quiz.participantes')->name('participantes');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('auth.admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('questions.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('questions.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $question = new Question();
        $question->question_type = $request->get('question_type');
        $question->content = $request->get('content');

        if($question->save()){

            if($request->get('question_type') === 'abierta'){
                $answer = new Answer();
                $answer->text = '';
                $answer->image = '';
                $answer->is_correct = 0;
                $answer->question_id = $question->id;
                $answer->save();
            }

            return redirect()->route('questions.edit', ['id' => $question->id])->with('saved', true);
        } else return redirect()->route('questions.create')->with('saved', false);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $question = Question::find($id);
        return view('questions.form', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $question = Question::find($id);
        $question->content = $request->get('content');
        if($question->save()){
            return redirect()->route('questions.edit', ['id' => $question->id])->with('saved', true);
        } else return redirect()->route('questions.create')->with('saved', false);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/questions/form.blade.php
@php
    $form_route = isset($question) ? route('questions.update', $question->id) : route('questions.store');
    $table_cols = [
        'id' => ['data' => 'id', 'name' => 'id'],
        'text' => ['data' => 'text', 'name' => 'text'],
        'img' => ['data' => 'img', 'name' => 'img', 'searchable' => false, 'orderable' => false],
        'options' => ['data' => 'options', 'name' => 'options', 'searchable' => false, 'orderable' => false],
        'is_correct' => ['data' => 'is_correct', 'name' => 'is_correct']
    ];
@endphp

@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-sm-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('questions.index') }}">Listado Preguntas</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Pregunta</li>
                </ol>
            </nav>
        </div>
        @if(session()->has('saved') && session('saved'))
            <div class="col-sm-12">
                <div class="alert alert-success" role="alert">
                    Datos guardados correctamente.
                </div>
            </div>
        @elseif(session()->has('saved') && !session('saved'))
            <div class="col-sm-12">
                <div class="alert alert-danger" role="alert">
                    Hubo un problema al guardar.
                </div>
            </div>
        @endif
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">Datos</div>

                <div class="card-body">
                    <form action="{{ $form_route }}" method="POST">
                        @isset($question)
                            @method('PUT')
                        @endisset
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="content">Pregunta</label>
                            <input type="text" class="form-control" name="content" value="{{ isset($question) ? $question->content : null }}">
                        </div>
                        <div class="form-group">
                            <label for="question_type">Tipo</label>
                            <select class="form-control" name="question_type" @isset($question) disabled @endisset>
                                <option value="opcion" {{ isset($question) && $question->question_type == 'opcion' ? 'selected' : '' }}>Opción</option>
                                <option value="abierta" {{ isset($question) && $question->question_type == 'abierta' ? 'selected' : '' }}>Abierta</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </form>
                </div>
            </div>
        </div>
        <br>
        @if(isset($question) && $question->question_type == 'opcion')
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            Preguntas
                        </div>
                        <div class="float-right">
                            <a href="{{ route('questions.answers.create', ['question' => $question->id]) }}" class="btn btn-primary" role="button"><i class="fas fa-plus-square"></i>&nbsp;&nbsp;Agregar Respuesta</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table>
                            <table id="table"  class="table table-striped table-bordered" style="width:100%" data-url="{{ route('datatable.answers', $question->id) }}">
                                <thead>
                                <tr>
                                    <th data-column='@json($table_cols['id'])'>id</th>
                                    <th data-column='@json($table_cols['text'])'>texto</th>
                                    <th data-column='@json($table_cols['img'])'>imagen</th>
                                    <th data-column='@json($table_cols['is_correct'])'>¿Correcto?</th>
                                    <th data-column='@json($table_cols['options'])'>editar</th>
                                </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </table>
                    </div>
                </div>
            </div>
        @endisset
    </div>
@endsection

resources/views/questions/index.blade.php
@php
    $table_cols = [
        'control' => [ 'className' =>  'details-control', 'orderable' =>  false, 'searchable' =>  false, 'data' =>  null, 'defaultContent' =>  ''],
        'id' => ['data' => 'id', 'name' => 'id'],
        'type' => ['data' => 'question_type', 'name' => 'question_type'],
        'question' => ['data' => 'content', 'name' => 'content'],
        'options' => ['data' => 'options', 'name' => 'options', 'orderable' => false, 'searcheable' => false]
    ];

    $table_cols_detail = [
        ['data' => 'id', 'name' => 'id'],
        ['data' => 'text', 'name' => 'text'],
        ['data' => 'img', 'name' => 'img', 'searchable' => false, 'orderable' => false],
        ['data' => 'options', 'name' => 'options', 'searchable' => false, 'orderable' => false],
        ['data' => 'is_correct', 'name' => 'is_correct']
    ];
@endphp
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="col-sm-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Listado Preguntas</li>
                </ol>
            </nav>
        </div>
        <div class="float-right">
            <a href="{{ route('questions.create') }}" class="btn btn-primary" role="button"><i class="fas fa-plus-square"></i>&nbsp;&nbsp;Agregar Pregunta</a>
        </div>
        <br>
        <br>
        <div class="col-sm-12">
            <table id="table"  class="table table-striped table-bordered" style="width:100%" data-url="{{ route('datatable.questions') }}">
                <thead>
                    <tr>
                        <th data-column='@json($table_cols['id'])'>id</th>
                        <th data-column='@json($table_cols['control'])'></th>
                        <th data-column='@json($table_cols['question'])'>Pregunta</th>
                        <th data-column='@json($table_cols['type'])'>Tipo</th>
                        <th data-column='@json($table_cols['options'])'>Opciones</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        window.detail_columns = @json($table_cols_detail);
    </script>
    <script src="{{ mix('js/detail.js') }}"></script>
@endpush

resources/views/questions/options.blade.php
<a href="{{ route('questions.edit', $row->id) }}" class="btn btn-secondary"><i class="text-white fas fa-edit"></i></a>